/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.alfonlevi.mahasiswa.view.updatepassword;

import id.alfonlevi.mahasiswa.controller.UpdatePasswordController;

import javax.swing.JComponent;
import javax.swing.border.EmptyBorder;

/**
 * @author LENOVO
 */
public class UpdatePasswordDialog extends javax.swing.JDialog implements UpdatePasswordView {
    private UpdatePasswordController mController;

    /**
     * Creates new form UpdatedPasswordDialog
     */
    public UpdatePasswordDialog() {
        initComponents();
        setModal(true);

        mController = new UpdatePasswordController(this);

        ((JComponent) getContentPane()).setBorder(new EmptyBorder(5, 5, 5, 5));
    }

    @Override
    public void setError(String error) {
        mErrorLabel.setText(error);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mPasswordLamaLabel = new javax.swing.JLabel();
        mPasswordBaruLabel = new javax.swing.JLabel();
        mKonfirmasiPasswordBaruLabel = new javax.swing.JLabel();
        mActionButton = new javax.swing.JButton();
        mErrorLabel = new javax.swing.JLabel();
        mPasswordLamaTextField = new javax.swing.JPasswordField();
        mPasswordBaruTextField = new javax.swing.JPasswordField();
        mLabelPasswordBaruTextField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update Password");
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        mPasswordLamaLabel.setText("Password Lama");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(mPasswordLamaLabel, gridBagConstraints);

        mPasswordBaruLabel.setText("Password Baru");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(mPasswordBaruLabel, gridBagConstraints);

        mKonfirmasiPasswordBaruLabel.setText("Konfirmasi Password Baru");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(mKonfirmasiPasswordBaruLabel, gridBagConstraints);

        mActionButton.setText("Ubah");
        mActionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mActionButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        getContentPane().add(mActionButton, gridBagConstraints);

        mErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        mErrorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(mErrorLabel, gridBagConstraints);

        mPasswordLamaTextField.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        getContentPane().add(mPasswordLamaTextField, gridBagConstraints);

        mPasswordBaruTextField.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        getContentPane().add(mPasswordBaruTextField, gridBagConstraints);

        mLabelPasswordBaruTextField.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        getContentPane().add(mLabelPasswordBaruTextField, gridBagConstraints);

        setSize(new java.awt.Dimension(414, 187));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mActionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mActionButtonActionPerformed
        if (mController.submit(mPasswordLamaTextField.getText(), mPasswordBaruTextField.getText(), mLabelPasswordBaruTextField.getText()))
            dispose();
    }//GEN-LAST:event_mActionButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton mActionButton;
    private javax.swing.JLabel mErrorLabel;
    private javax.swing.JLabel mKonfirmasiPasswordBaruLabel;
    private javax.swing.JPasswordField mLabelPasswordBaruTextField;
    private javax.swing.JLabel mPasswordBaruLabel;
    private javax.swing.JPasswordField mPasswordBaruTextField;
    private javax.swing.JLabel mPasswordLamaLabel;
    private javax.swing.JPasswordField mPasswordLamaTextField;
    // End of variables declaration//GEN-END:variables
}
