/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.alfonlevi.mahasiswa.view.nilaimahasiswa;

import id.alfonlevi.mahasiswa.controller.NilaiMahasiswaController;
import id.alfonlevi.mahasiswa.data.model.Periode;
import id.alfonlevi.mahasiswa.view.base.MenuHelper;
import id.alfonlevi.mahasiswa.view.base.PeriodeListCellRenderer;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.table.TableModel;

/**
 * @author LENOVO
 */
public class NilaiMahasiswaFrame extends javax.swing.JFrame implements NilaiMahasiswaView {
    private NilaiMahasiswaController mController;

    /**
     * Creates new form NilaiMahasiswaFrame
     */
    public NilaiMahasiswaFrame() {
        initComponents();
        mPeriodeComboBox.setRenderer(new PeriodeListCellRenderer());

        mController = new NilaiMahasiswaController(this);

        ((JComponent) getContentPane()).setBorder(new EmptyBorder(5, 5, 5, 5));

        MenuHelper.applyMenu(this, false);
    }

    @Override
    public void setPeriodeModel(ComboBoxModel<Periode> model) {
        mPeriodeComboBox.setModel(model);
    }

    @Override
    public void setTableModel(TableModel model) {
        mTable.setModel(model);
    }

    @Override
    public void setError(String error) {
        mErrorLabel.setText(error);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mNimLabel = new javax.swing.JLabel();
        mNimField = new javax.swing.JTextField();
        mNamaLabel = new javax.swing.JLabel();
        mNamaField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        mTable = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        mPeriodeComboBox = new javax.swing.JComboBox<>();
        mPeriodeLabel = new javax.swing.JLabel();
        mShowButton = new javax.swing.JButton();
        mErrorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lihat Nilai Mahasiswa");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        mNimLabel.setText("NIM");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(mNimLabel, gridBagConstraints);

        mNimField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mNimFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(mNimField, gridBagConstraints);

        mNamaLabel.setText("Nama");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(mNamaLabel, gridBagConstraints);

        mNamaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mNamaFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(mNamaField, gridBagConstraints);

        mTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String[]{
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane1.setViewportView(mTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jScrollPane1, gridBagConstraints);
        getContentPane().add(jTabbedPane1, new java.awt.GridBagConstraints());

        mPeriodeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPeriodeComboBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(mPeriodeComboBox, gridBagConstraints);

        mPeriodeLabel.setText("Periode");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(mPeriodeLabel, gridBagConstraints);

        mShowButton.setText("Tampilkan");
        mShowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mShowButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(mShowButton, gridBagConstraints);

        mErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(mErrorLabel, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mNimFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mNimFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mNimFieldActionPerformed

    private void mNamaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mNamaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mNamaFieldActionPerformed

    private void mPeriodeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPeriodeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mPeriodeComboBoxActionPerformed

    private void mShowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mShowButtonActionPerformed
        mController.show(mNimField.getText(), mNamaField.getText());
    }//GEN-LAST:event_mShowButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel mErrorLabel;
    private javax.swing.JTextField mNamaField;
    private javax.swing.JLabel mNamaLabel;
    private javax.swing.JTextField mNimField;
    private javax.swing.JLabel mNimLabel;
    private javax.swing.JComboBox<Periode> mPeriodeComboBox;
    private javax.swing.JLabel mPeriodeLabel;
    private javax.swing.JButton mShowButton;
    private javax.swing.JTable mTable;
    // End of variables declaration//GEN-END:variables
}
