/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.alfonlevi.mahasiswa.view.main;

import id.alfonlevi.mahasiswa.view.mahasiswa.MahasiswaPanel;
import id.alfonlevi.mahasiswa.view.matakuliah.MataKuliahPanel;
import javax.swing.table.TableModel;

/**
 *
 * @author levir
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainFrame() {
        initComponents();
        
        mTabPane.add("Siswa", new MahasiswaPanel());
        mTabPane.add("Mata Kuliah", new MataKuliahPanel());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mTabPane = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        mTabPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        getContentPane().add(mTabPane);

        setSize(new java.awt.Dimension(414, 308));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane mTabPane;
    // End of variables declaration//GEN-END:variables
}
