/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package id.alfonlevi.mahasiswa.view.kelas;

import com.formdev.flatlaf.FlatClientProperties;
import id.alfonlevi.mahasiswa.controller.KelasController;
import id.alfonlevi.mahasiswa.view.editkelas.EditKelasDialog;

import javax.swing.table.TableModel;

/**
 *
 * @author levir
 */
public class KelasPanel extends javax.swing.JPanel implements KelasView {
    private KelasController mController;
    
    /**
     * Creates new form KelasPanel
     */
    public KelasPanel(String id) {
        initComponents();

        mTitleLabel.putClientProperty(FlatClientProperties.STYLE_CLASS, "h2");
        
        mController = new KelasController(this, id);
        
    }

    @Override
    public void setTitle(String title) {
        mTitleLabel.setText(title);
    }

    @Override
    public void setTableModel(TableModel model) {
        mTable.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mTitleLabel = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        mEditButton = new javax.swing.JButton();
        mDeleteButton = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5));
        jScrollPane1 = new javax.swing.JScrollPane();
        mTable = new javax.swing.JTable();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5));
        jPanel2 = new javax.swing.JPanel();
        mEditAnggota = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        mTitleLabel.setText("jLabel1");
        jPanel1.add(mTitleLabel);
        jPanel1.add(filler1);

        mEditButton.setText("Ubah");
        mEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEditButtonActionPerformed(evt);
            }
        });
        jPanel1.add(mEditButton);

        mDeleteButton.setText("Hapus");
        jPanel1.add(mDeleteButton);

        add(jPanel1);
        add(filler2);

        jScrollPane1.setAlignmentX(0.0F);
        jScrollPane1.setAlignmentY(0.0F);

        mTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(mTable);

        add(jScrollPane1);
        add(filler3);

        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.X_AXIS));

        mEditAnggota.setText("Ubah Anggota");
        jPanel2.add(mEditAnggota);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private void mEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mEditButtonActionPerformed
        new EditKelasDialog(mController.getId(), null).setVisible(true);
    }//GEN-LAST:event_mEditButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mDeleteButton;
    private javax.swing.JButton mEditAnggota;
    private javax.swing.JButton mEditButton;
    private javax.swing.JTable mTable;
    private javax.swing.JLabel mTitleLabel;
    // End of variables declaration//GEN-END:variables
}
