/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package id.alfonlevi.mahasiswa.view.dosen;

import com.formdev.flatlaf.FlatClientProperties;
import id.alfonlevi.mahasiswa.controller.DosenController;
import id.alfonlevi.mahasiswa.view.base.DisposableView;
import id.alfonlevi.mahasiswa.view.editdosen.EditDosenDialog;

import javax.swing.*;
import javax.swing.table.TableModel;

/**
 * @author levir
 */
public class DosenPanel extends javax.swing.JPanel implements DosenView, DisposableView {
    private DosenController mController;

    /**
     * Creates new form DosenPanel
     */
    public DosenPanel() {
        initComponents();
        mController = new DosenController(this);

        mTitleLabel.putClientProperty(FlatClientProperties.STYLE_CLASS, "h2");
    }

    @Override
    public void dispose() {
        mController.dispose();
    }

    @Override
    public void setTableModel(TableModel model, ListSelectionModel selectionModel) {
        mTable.setModel(model);
        mTable.setSelectionModel(selectionModel);
    }

    @Override
    public void showError(String message) {
        JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mTitleLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        mAddButton = new javax.swing.JButton();
        mEditButton = new javax.swing.JButton();
        mDeleteButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        mTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mTitleLabel.setText("Dosen");
        add(mTitleLabel);

        jPanel2.setAlignmentX(0.0F);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.X_AXIS));

        jScrollPane1.setAlignmentY(0.0F);

        mTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(mTable);

        jPanel2.add(jScrollPane1);

        jPanel1.setAlignmentY(0.0F);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        mAddButton.setText("Tambah");
        mAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAddButtonActionPerformed(evt);
            }
        });
        jPanel1.add(mAddButton);

        mEditButton.setText("Ubah");
        mEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEditButtonActionPerformed(evt);
            }
        });
        jPanel1.add(mEditButton);

        mDeleteButton.setText("Hapus");
        mDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mDeleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(mDeleteButton);

        jPanel2.add(jPanel1);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private void mAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAddButtonActionPerformed
        new EditDosenDialog(null).setVisible(true);
    }//GEN-LAST:event_mAddButtonActionPerformed

    private void mEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mEditButtonActionPerformed
        var id = mController.getSelectedUsername();
        if (id != null) new EditDosenDialog(id).setVisible(true);
    }//GEN-LAST:event_mEditButtonActionPerformed

    private void mDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mDeleteButtonActionPerformed
        mController.deleteSelected();
    }//GEN-LAST:event_mDeleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mAddButton;
    private javax.swing.JButton mDeleteButton;
    private javax.swing.JButton mEditButton;
    private javax.swing.JTable mTable;
    private javax.swing.JLabel mTitleLabel;
    // End of variables declaration//GEN-END:variables
}
