/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.alfonlevi.mahasiswa.view.editanggotakelas;

import id.alfonlevi.mahasiswa.controller.EditAnggotaKelasController;
import javax.swing.JComponent;
import javax.swing.border.EmptyBorder;

import javax.swing.table.TableModel;

/**
 *
 * @author levir
 */
public class EditAnggotaKelasDialog extends javax.swing.JDialog implements  EditAnggotaKelasView {
    private EditAnggotaKelasController mController;

    /**
     * Creates new form EditAnggotaKelasDialog
     */
    public EditAnggotaKelasDialog(String id) {
        initComponents();

        setModal(true);

        mController = new EditAnggotaKelasController(id, this);
        
        ((JComponent) getContentPane()).setBorder(new EmptyBorder(5, 5, 5, 5));
    }

    @Override
    public void setTableModel(TableModel model) {
        mTable.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        mSaveButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ubah Anggota Kelas");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jScrollPane1.setAlignmentX(0.0F);
        jScrollPane1.setAlignmentY(0.0F);

        mTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(mTable);

        getContentPane().add(jScrollPane1);

        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        mSaveButton.setText("Simpan");
        mSaveButton.setToolTipText("");
        mSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSaveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(mSaveButton);

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSaveButtonActionPerformed
        if (mController.submit())
            dispose();
    }//GEN-LAST:event_mSaveButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mSaveButton;
    private javax.swing.JTable mTable;
    // End of variables declaration//GEN-END:variables
}
