/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.alfonlevi.mahasiswa.view.periode;

import id.alfonlevi.mahasiswa.controller.PeriodeController;
import id.alfonlevi.mahasiswa.data.model.Periode;
import id.alfonlevi.mahasiswa.view.base.PeriodeListCellRenderer;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author levir
 */
public class PeriodeFrame extends javax.swing.JFrame implements PeriodeView {
    private final PeriodeController mController;

    /**
     * Creates new form PeriodeFrame
     */
    public PeriodeFrame() {
        initComponents();
        mList.setCellRenderer(new PeriodeListCellRenderer());

        mController = new PeriodeController(this);
    }

    @Override
    public void setListModel(ListModel<Periode> listModel) {
        mList.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mList = new javax.swing.JList<>();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0));
        jPanel1 = new javax.swing.JPanel();
        mAddButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        jScrollPane1.setAlignmentY(0.0F);
        jScrollPane1.setViewportView(mList);

        getContentPane().add(jScrollPane1);
        getContentPane().add(filler1);

        jPanel1.setAlignmentY(0.0F);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        mAddButton.setText("Tambah");
        jPanel1.add(mAddButton);

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mAddButton;
    private javax.swing.JList<Periode> mList;
    // End of variables declaration//GEN-END:variables
}
