/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.alfonlevi.mahasiswa.view.periode;

import id.alfonlevi.mahasiswa.controller.PeriodeController;
import id.alfonlevi.mahasiswa.data.model.Periode;
import id.alfonlevi.mahasiswa.view.base.PeriodeListCellRenderer;
import id.alfonlevi.mahasiswa.view.editperiode.EditPeriodeDialog;

import javax.swing.*;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author levir
 */
public class PeriodeDialog extends javax.swing.JDialog implements PeriodeView {
    private final PeriodeController mController;

    /**
     * Creates new form PeriodeFrame
     */
    public PeriodeDialog() {
        initComponents();
        mList.setCellRenderer(new PeriodeListCellRenderer());
        setModal(true);
        mController = new PeriodeController(this);

        ((JComponent) getContentPane()).setBorder(new EmptyBorder(5, 5, 5, 5));
    }

    @Override
    public void setListModel(ListModel<Periode> listModel, ListSelectionModel selectionModel) {
        mList.setModel(listModel);
        mList.setSelectionModel(selectionModel);
    }

    @Override
    public void showError(String error) {
        JOptionPane.showMessageDialog(this, error, "Error", JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public void dispose() {
        mController.dispose();
        super.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mList = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        mAddButton = new javax.swing.JButton();
        mEditButton = new javax.swing.JButton();
        mDeleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manajemen Periode");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        jScrollPane1.setAlignmentY(0.0F);
        jScrollPane1.setViewportView(mList);

        getContentPane().add(jScrollPane1);

        jPanel1.setAlignmentY(0.0F);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        mAddButton.setText("Tambah");
        mAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAddButtonActionPerformed(evt);
            }
        });
        jPanel1.add(mAddButton);

        mEditButton.setText("Ubah");
        mEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEditButtonActionPerformed(evt);
            }
        });
        jPanel1.add(mEditButton);

        mDeleteButton.setText("Hapus");
        mDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mDeleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(mDeleteButton);

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAddButtonActionPerformed
        new EditPeriodeDialog(null).setVisible(true);
    }//GEN-LAST:event_mAddButtonActionPerformed

    private void mEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mEditButtonActionPerformed
        var id = mController.getSelectedId();
        if (id == null) return;
        new EditPeriodeDialog(id).setVisible(true);
    }//GEN-LAST:event_mEditButtonActionPerformed

    private void mDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mDeleteButtonActionPerformed
        mController.deleteSelected();
    }//GEN-LAST:event_mDeleteButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mAddButton;
    private javax.swing.JButton mDeleteButton;
    private javax.swing.JButton mEditButton;
    private javax.swing.JList<Periode> mList;
    // End of variables declaration//GEN-END:variables
}
