/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.alfonlevi.mahasiswa.view.editmatakuliah;

import id.alfonlevi.mahasiswa.controller.EditMataKuliahController;
import id.alfonlevi.mahasiswa.data.model.MataKuliah;
import javax.swing.JComponent;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author levir
 */
public class EditMataKuliahDialog extends javax.swing.JDialog implements EditMataKuliahView {
    private EditMataKuliahController mController;

    /**
     * Creates new form EditMataKuliahFrame
     */
    public EditMataKuliahDialog(String id, String periodeId) {
        initComponents();
        
        setModal(true);

        mController = new EditMataKuliahController(this, id, periodeId);
        
        ((JComponent) getContentPane()).setBorder(new EmptyBorder(5, 5, 5, 5));
    }

    public EditMataKuliahController getController() {
        return mController;
    }

    @Override
    public void showData(boolean isNew, MataKuliah mahasiswa) {
        if (isNew) {
            setTitle("Buat Mata Kuliah");
            mActionButton.setText("Buat");
        } else {
            setTitle("Ubah Mata Kuliah");
            mActionButton.setText("Ubah");

            mNamaField.setText(mahasiswa.getNama());
        }
    }

    @Override
    public void showError(String error) {
        mErrorLabel.setText(error);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mNamaLabel = new javax.swing.JLabel();
        mNamaField = new javax.swing.JTextField();
        mErrorLabel = new javax.swing.JLabel();
        mActionButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        mNamaLabel.setText("Nama");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        getContentPane().add(mNamaLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        getContentPane().add(mNamaField, gridBagConstraints);

        mErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        mErrorLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        getContentPane().add(mErrorLabel, gridBagConstraints);

        mActionButton.setText("Tambah");
        mActionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mActionButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        getContentPane().add(mActionButton, gridBagConstraints);

        setSize(new java.awt.Dimension(414, 125));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mActionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mActionButtonActionPerformed
        if (mController.submit(mNamaField.getText())) {
            dispose();
        }
    }//GEN-LAST:event_mActionButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton mActionButton;
    private javax.swing.JLabel mErrorLabel;
    private javax.swing.JTextField mNamaField;
    private javax.swing.JLabel mNamaLabel;
    // End of variables declaration//GEN-END:variables
}
