/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package id.alfonlevi.mahasiswa.view.matakuliahlist;

import com.formdev.flatlaf.FlatClientProperties;
import id.alfonlevi.mahasiswa.controller.MataKuliahListController;
import id.alfonlevi.mahasiswa.data.model.MataKuliah;
import id.alfonlevi.mahasiswa.view.editmatakuliah.EditMataKuliahDialog;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import java.util.List;

/**
 *
 * @author levir
 */
public class MataKuliahListPanel extends javax.swing.JPanel implements MataKuliahListView {
    private JLabel mEmptyLabel =  new JLabel("Belum ada mata kuliah", SwingConstants.CENTER);
    private MataKuliahListController mController;

    /**
     * Creates new form MataKuliahPanel
     */
    public MataKuliahListPanel() {
        initComponents();
        
        var boxLayout = Box.createVerticalBox();
        boxLayout.setBorder(BorderFactory.createEmptyBorder(0, 5, 0, 5));
        
        var titleLabel = new JLabel();
        titleLabel.setText("Mata Kuliah");
        titleLabel.putClientProperty(FlatClientProperties.STYLE_CLASS, "h2");
        boxLayout.add(titleLabel);
        
        var addButton = new JButton();
        addButton.setText("Tambah");
        addButton.addActionListener((v) -> {
            var frame = new EditMataKuliahDialog();
            frame.getController().setup(null);
            frame.setVisible(true);
        });
        boxLayout.add(addButton);
        
        mTabPane.putClientProperty(FlatClientProperties.TABBED_PANE_LEADING_COMPONENT, boxLayout);
        mTabPane.putClientProperty(FlatClientProperties.TABBED_PANE_SHOW_CONTENT_SEPARATOR,true);
        mTabPane.putClientProperty(FlatClientProperties.TABBED_PANE_MINIMUM_TAB_WIDTH, 125);

        mController = new MataKuliahListController(this);
    }

    @Override
    public void setData(List<MataKuliah> data) {
        mTabPane.removeAll();
        if (data.isEmpty()) {
            mTabPane.add("Masih Kosong", mEmptyLabel);
        } else {
            for (var mataKuliah : data) {
                mTabPane.add(mataKuliah.getNama(), new JLabel(mataKuliah.getNama()));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mTabPane = new javax.swing.JTabbedPane();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        mTabPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        add(mTabPane);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane mTabPane;
    // End of variables declaration//GEN-END:variables
}
