/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.alfonlevi.mahasiswa.view.editdosen;

import id.alfonlevi.mahasiswa.controller.EditDosenController;
import id.alfonlevi.mahasiswa.data.model.Dosen;

/**
 * @author LENOVO
 */
public class EditDosenDialog extends javax.swing.JDialog implements EditDosenView {
    private final EditDosenController mController;

    /**
     * Creates new form EditDosenDialog
     */
    public EditDosenDialog(String username) {
        initComponents();
        setModal(true);
        mController = new EditDosenController(this, username);
    }

    @Override
    public void showData(boolean isNew, Dosen dosen) {
        if (!isNew) {
            mNipField.setText(dosen.getNip());
            mUsernameField.setText(dosen.getUsername());
            mUsernameField.setEditable(false);
            mNamaField.setText(dosen.getNama());
            mPasswordField.setVisible(false);
            mPasswordLabel.setVisible(false);
            mActionButton.setText("Ubah");
        }
        setTitle(isNew ? "Tambar Dosen" : "Ubah Dosen");
    }

    @Override
    public void showError(String error) {
        mErrorLabel.setText(error);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mNipLabel = new javax.swing.JLabel();
        mNipField = new javax.swing.JTextField();
        mUsernameLabel = new javax.swing.JLabel();
        mUsernameField = new javax.swing.JTextField();
        mNamalabel = new javax.swing.JLabel();
        mNamaField = new javax.swing.JTextField();
        mPasswordLabel = new javax.swing.JLabel();
        mPasswordField = new javax.swing.JTextField();
        mErrorLabel = new javax.swing.JLabel();
        mActionButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        mNipLabel.setText("NIP");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(mNipLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        getContentPane().add(mNipField, gridBagConstraints);

        mUsernameLabel.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(mUsernameLabel, gridBagConstraints);

        mUsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mUsernameFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        getContentPane().add(mUsernameField, gridBagConstraints);

        mNamalabel.setText("Nama");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(mNamalabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        getContentPane().add(mNamaField, gridBagConstraints);

        mPasswordLabel.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(mPasswordLabel, gridBagConstraints);

        mPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPasswordFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        getContentPane().add(mPasswordField, gridBagConstraints);

        mErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        mErrorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mErrorLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(mErrorLabel, gridBagConstraints);

        mActionButton.setText("Tambah");
        mActionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mActionButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        getContentPane().add(mActionButton, gridBagConstraints);

        setSize(new java.awt.Dimension(439, 308));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mPasswordFieldActionPerformed

    private void mUsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mUsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mUsernameFieldActionPerformed

    private void mActionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mActionButtonActionPerformed
        if (mController.submit(mUsernameField.getText(), mNipField.getText(), mNamaField.getText(), mPasswordField.getText())) {
            dispose();
        }
    }//GEN-LAST:event_mActionButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton mActionButton;
    private javax.swing.JLabel mErrorLabel;
    private javax.swing.JTextField mNamaField;
    private javax.swing.JLabel mNamalabel;
    private javax.swing.JTextField mNipField;
    private javax.swing.JLabel mNipLabel;
    private javax.swing.JTextField mPasswordField;
    private javax.swing.JLabel mPasswordLabel;
    private javax.swing.JTextField mUsernameField;
    private javax.swing.JLabel mUsernameLabel;
    // End of variables declaration//GEN-END:variables
}
