/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.alfonlevi.mahasiswa.view.editmahasiswa;

import id.alfonlevi.mahasiswa.controller.EditMahasiswaController;
import id.alfonlevi.mahasiswa.data.model.Mahasiswa;

/**
 *
 * @author levir
 */
public class EditMahasiswaDialog extends javax.swing.JDialog implements EditMahasiswaView {
    private EditMahasiswaController mController;
    
    /**
     * Creates new form EditMahasiswaFrame
     */
    public EditMahasiswaDialog(String id) {
        initComponents();
        
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        mController = new EditMahasiswaController(this, id);
        setModal(true);
    }

    public EditMahasiswaController getController() {
        return mController;
    }

    @Override
    public void showData(boolean isNew, Mahasiswa mahasiswa) {
        if (isNew) {
            mActionButton.setText("Tambah");
            mNimField.setEditable(true);
            setTitle("Tambah Mahasiswa");
        } else {
            mActionButton.setText("Edit");
            mNimField.setText(mahasiswa.getNim());
            mNimField.setEditable(false);
            mNamaField.setText(mahasiswa.getNama());
            setTitle("Ubah Mahasiswa");
        }
    }

    @Override
    public void showError(String error) {
        mErrorLabel.setText(error);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mNimLabel = new javax.swing.JLabel();
        mNimField = new javax.swing.JTextField();
        mNamaLabel = new javax.swing.JLabel();
        mNamaField = new javax.swing.JTextField();
        mErrorLabel = new javax.swing.JLabel();
        mActionButton = new javax.swing.JButton();
        mErroLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        mNimLabel.setText("NIM");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        getContentPane().add(mNimLabel, gridBagConstraints);

        mNimField.setAlignmentX(0.0F);
        mNimField.setMaximumSize(new java.awt.Dimension(2147483647, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        getContentPane().add(mNimField, gridBagConstraints);

        mNamaLabel.setText("Nama");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        getContentPane().add(mNamaLabel, gridBagConstraints);

        mNamaField.setAlignmentX(0.0F);
        mNamaField.setMaximumSize(new java.awt.Dimension(2147483647, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        getContentPane().add(mNamaField, gridBagConstraints);

        mErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        getContentPane().add(mErrorLabel, gridBagConstraints);

        mActionButton.setText("Tambah");
        mActionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mActionButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        getContentPane().add(mActionButton, gridBagConstraints);

        mErroLabel.setForeground(new java.awt.Color(255, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(mErroLabel, gridBagConstraints);

        setSize(new java.awt.Dimension(414, 155));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mActionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mActionButtonActionPerformed
        if (mController.submit(mNimField.getText(), mNamaField.getText())) {
            dispose();
        }
    }//GEN-LAST:event_mActionButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton mActionButton;
    private javax.swing.JLabel mErroLabel;
    private javax.swing.JLabel mErrorLabel;
    private javax.swing.JTextField mNamaField;
    private javax.swing.JLabel mNamaLabel;
    private javax.swing.JTextField mNimField;
    private javax.swing.JLabel mNimLabel;
    // End of variables declaration//GEN-END:variables
}
