/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.alfonlevi.mahasiswa.view.login;

import id.alfonlevi.mahasiswa.controller.LoginController;
import id.alfonlevi.mahasiswa.data.model.Akun;
import id.alfonlevi.mahasiswa.view.base.MenuHelper;
import id.alfonlevi.mahasiswa.view.main.MainFrame;
import id.alfonlevi.mahasiswa.view.maindosen.MainDosenFrame;
import id.alfonlevi.mahasiswa.view.nilaimahasiswa.NilaiMahasiswaFrame;

import javax.swing.*;
import javax.swing.border.EmptyBorder;

/**
 * @author LENOVO
 */
public class LoginFrame extends javax.swing.JFrame implements LoginView {
    private LoginController mController;

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        mController = new LoginController(this);
        
        ((JComponent)getContentPane()).setBorder(new EmptyBorder(5, 5, 5, 5));

        MenuHelper.applyMenu(this, false);
    }

    @Override
    public void showError(String error) {
        mErrorLabel.setText(error);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mUsernameField = new javax.swing.JTextField();
        mUsernameLabel = new javax.swing.JLabel();
        mPasswordLabel = new javax.swing.JLabel();
        mErrorLabel = new javax.swing.JLabel();
        mLoginButton = new javax.swing.JButton();
        mLihatNilaiButton = new javax.swing.JButton();
        mPasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        mUsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mUsernameFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        getContentPane().add(mUsernameField, gridBagConstraints);

        mUsernameLabel.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(mUsernameLabel, gridBagConstraints);

        mPasswordLabel.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(mPasswordLabel, gridBagConstraints);

        mErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        mErrorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mErrorLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        getContentPane().add(mErrorLabel, gridBagConstraints);

        mLoginButton.setText("Login");
        mLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLoginButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        getContentPane().add(mLoginButton, gridBagConstraints);

        mLihatNilaiButton.setText("Lihat Nilai Mahasiswa");
        mLihatNilaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLihatNilaiButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        getContentPane().add(mLihatNilaiButton, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        getContentPane().add(mPasswordField, gridBagConstraints);

        setSize(new java.awt.Dimension(414, 191));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mUsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mUsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mUsernameFieldActionPerformed

    private void mLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mLoginButtonActionPerformed
        var result = mController.login(mUsernameField.getText(), mPasswordField.getText());
        if (result.isEmpty()) return;
        if (result.get() == Akun.Role.ADMIN) new MainFrame().setVisible(true);
        if (result.get() == Akun.Role.DOSEN) new MainDosenFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_mLoginButtonActionPerformed

    private void mLihatNilaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mLihatNilaiButtonActionPerformed
        new NilaiMahasiswaFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_mLihatNilaiButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel mErrorLabel;
    private javax.swing.JButton mLihatNilaiButton;
    private javax.swing.JButton mLoginButton;
    private javax.swing.JPasswordField mPasswordField;
    private javax.swing.JLabel mPasswordLabel;
    private javax.swing.JTextField mUsernameField;
    private javax.swing.JLabel mUsernameLabel;
    // End of variables declaration//GEN-END:variables
}
