/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.alfonlevi.mahasiswa.view.editperiode;

import id.alfonlevi.mahasiswa.controller.EditPeriodeController;
import id.alfonlevi.mahasiswa.data.model.Periode;

import javax.swing.*;
import java.awt.*;
import java.util.List;

/**
 *
 * @author levir
 */
public class EditPeriodeDialog extends javax.swing.JDialog implements EditPeriodeView {
    private final EditPeriodeController mController;

    /**
     * Creates new form EditPeriodeDialog
     */
    public EditPeriodeDialog(String id) {
        initComponents();
        setModal(true);
        mTahunComboBox.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(
                    JList<?> list,
                    Object value,
                    int index,
                    boolean isSelected,
                    boolean cellHasFocus
            ) {
                if (value instanceof Integer) {
                    int tahun = ((Integer) value);
                    value = String.format("%d/%d", tahun, tahun + 1);
                }
                return super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            }
        });

        mController = new EditPeriodeController(this, id);
    }

    @Override
    public void setData(Periode periode, boolean isNew) {
        if (isNew) {
            mActionButton.setText("Tambah");
            setTitle("Tambah Periode");
        } else {
            mActionButton.setText("Ubah");
            setTitle("Ubah Periode");
            mTahunComboBox.setSelectedItem(periode.getTahun());
            mSemesterComboBox.setSelectedItem(periode.getSemester());
        }
    }

    @Override
    public void setTahunModel(ComboBoxModel<Integer> model) {
        mTahunComboBox.setModel(model);
        mTahunComboBox.setSelectedIndex(-1);
    }

    @Override
    public void setSemesterModel(ComboBoxModel<String> model) {
        mSemesterComboBox.setModel(model);
        mSemesterComboBox.setSelectedIndex(-1);
    }

    @Override
    public void showError(String error) {
        mErrorLabel.setText(error);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mTahunLabel = new javax.swing.JLabel();
        mTahunComboBox = new javax.swing.JComboBox<>();
        mSemesterLabel = new javax.swing.JLabel();
        mSemesterComboBox = new javax.swing.JComboBox<>();
        mErrorLabel = new javax.swing.JLabel();
        mActionButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        mTahunLabel.setText("Tahun");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(mTahunLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        getContentPane().add(mTahunComboBox, gridBagConstraints);

        mSemesterLabel.setText("Semester");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(mSemesterLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        getContentPane().add(mSemesterComboBox, gridBagConstraints);

        mErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        getContentPane().add(mErrorLabel, gridBagConstraints);

        mActionButton.setText("Tambah");
        mActionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mActionButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        getContentPane().add(mActionButton, gridBagConstraints);

        setSize(new java.awt.Dimension(414, 149));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mActionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mActionButtonActionPerformed
       if (mController.submit()) {
           dispose();
       }
    }//GEN-LAST:event_mActionButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton mActionButton;
    private javax.swing.JLabel mErrorLabel;
    private javax.swing.JComboBox<String> mSemesterComboBox;
    private javax.swing.JLabel mSemesterLabel;
    private javax.swing.JComboBox<Integer> mTahunComboBox;
    private javax.swing.JLabel mTahunLabel;
    // End of variables declaration//GEN-END:variables
}
