/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package id.alfonlevi.mahasiswa.view.mahasiswa;

import com.formdev.flatlaf.FlatClientProperties;
import id.alfonlevi.mahasiswa.controller.MahasiswaController;
import id.alfonlevi.mahasiswa.view.base.DisposableView;
import id.alfonlevi.mahasiswa.view.editmahasiswa.EditMahasiswaDialog;

import javax.swing.*;
import javax.swing.table.TableModel;

/**
 *
 * @author levir
 */
public class MahasiswaPanel extends javax.swing.JPanel implements MahasiswaView, DisposableView {
    private MahasiswaController mController;
    
    /**
     * Creates new form SiswaView
     */
    public MahasiswaPanel() {
        initComponents();
        mController = new MahasiswaController(this);
        
        mTItleLabel.putClientProperty(FlatClientProperties.STYLE_CLASS, "h2");
    }

    @Override
    public void setTableModel(TableModel model, ListSelectionModel selectionModel) {
        mTable.setModel(model);
        mTable.setSelectionModel(selectionModel);
    }

    @Override
    public void showError(String error) {
        JOptionPane.showMessageDialog(this, error, "Error", JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public void dispose() {
        mController.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        mTable = new javax.swing.JTable();
        mAddButton = new javax.swing.JButton();
        mEditButton = new javax.swing.JButton();
        mDeleteButton = new javax.swing.JButton();
        mTItleLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        setLayout(new java.awt.GridBagLayout());

        mTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(mTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 2.0;
        add(jScrollPane1, gridBagConstraints);

        mAddButton.setText("Tambah");
        mAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAddButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        add(mAddButton, gridBagConstraints);

        mEditButton.setText("Edit");
        mEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEditButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        add(mEditButton, gridBagConstraints);

        mDeleteButton.setText("Delete");
        mDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mDeleteButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        add(mDeleteButton, gridBagConstraints);

        mTItleLabel.setText("Mahasiswa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(mTItleLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void mAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAddButtonActionPerformed
        new EditMahasiswaDialog(null).setVisible(true);
    }//GEN-LAST:event_mAddButtonActionPerformed

    private void mEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mEditButtonActionPerformed
        var nim = mController.getSelectedNim();
        if (nim == null) return;
        
        new EditMahasiswaDialog(nim).setVisible(true);
    }//GEN-LAST:event_mEditButtonActionPerformed

    private void mDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mDeleteButtonActionPerformed
        mController.deleteSelected();
    }//GEN-LAST:event_mDeleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mAddButton;
    private javax.swing.JButton mDeleteButton;
    private javax.swing.JButton mEditButton;
    private javax.swing.JLabel mTItleLabel;
    private javax.swing.JTable mTable;
    // End of variables declaration//GEN-END:variables
}
