/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package id.alfonlevi.mahasiswa.view.mahasiswa;

import id.alfonlevi.mahasiswa.controller.MahasiswaController;
import id.alfonlevi.mahasiswa.view.editmahasiswa.EditMahasiswaFrame;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author levir
 */
public class MahasiswaPanel extends javax.swing.JPanel implements MahasiswaView {
    private MahasiswaController mController;
    
    /**
     * Creates new form SiswaView
     */
    public MahasiswaPanel() {
        initComponents();
        mController = new MahasiswaController(this);
    }

    @Override
    public void setTableModel(TableModel model) {
        mTable.setModel(model);
    } 
    
    private String getSelectedNim() {
        var selected = mTable.getSelectedRow();
        
        if (selected == -1) {
            JOptionPane.showMessageDialog(this, "Tidak ada yang dipilih", "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        
        return (String) mTable.getModel().getValueAt(selected, 0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        mTable = new javax.swing.JTable();
        mAddButton = new javax.swing.JButton();
        mEditButton = new javax.swing.JButton();
        mDeleteButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        mTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(mTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 2.0;
        add(jScrollPane1, gridBagConstraints);

        mAddButton.setText("Tambah");
        mAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAddButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        add(mAddButton, gridBagConstraints);

        mEditButton.setText("Edit");
        mEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEditButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        add(mEditButton, gridBagConstraints);

        mDeleteButton.setText("Delete");
        mDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mDeleteButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        add(mDeleteButton, gridBagConstraints);

        jLabel1.setText("Siswa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(jLabel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void mAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAddButtonActionPerformed
        new EditMahasiswaFrame(null).setVisible(true);
    }//GEN-LAST:event_mAddButtonActionPerformed

    private void mEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mEditButtonActionPerformed
        var nim = getSelectedNim();
        if (nim == null) return;
        
        new EditMahasiswaFrame(nim).setVisible(true);
    }//GEN-LAST:event_mEditButtonActionPerformed

    private void mDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mDeleteButtonActionPerformed
        var nim = getSelectedNim();
        if (nim == null) return;
        
        mController.delete(nim);
    }//GEN-LAST:event_mDeleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mAddButton;
    private javax.swing.JButton mDeleteButton;
    private javax.swing.JButton mEditButton;
    private javax.swing.JTable mTable;
    // End of variables declaration//GEN-END:variables
}
